package it.unipi.iotplatform.qosbroker.api.datamodel;

public enum QoSReasonPhrase {

	OK_200("OK"), BADREQUEST_400("BAD REQUEST"), FORBIDDEN_403("FORBIDDEN"), CONTEXTELEMENTNOTFOUND_404(
			"CONTEXT ELEMENT NOT FOUND"), SUBSCRIPTIONIDNOTFOUND_470(
			"SUBSCRIPTION ID NOT FOUND"), MISSINGPARAMETER_471(
			"MISSING PARAMETER"), INVALIDPARAMETER_472("INVALID PARAMETER"), ERRORINMETADATA_473(
			"ERROR IN METADATA"), REGULAREXPRESSIONFORENTITYIDNOTALLOWED_480(
			"REGULAR EXPRESSION FOR ENTITYID NOT ALLOWED"), ENTITYTYPEREQUIRED_481(
			"ENTITY TYPE REQUIRED"), ATTRIBUTELISTREQUIRED_482(
			"ATTRIBUTE LIST REQUIRED"), RECEIVERINTERNALERROR_500(
			"RECEIVER INTERNAL ERROR"), SERVICEALLOCATIONFAILED_502("SERVICE AGREEMENT REQUEST CAN BE SATISFIED"),
			SERVICEALLOCATIONNOTFOUND_405("ALLOCATION SCHEMA NOT FOUND");

	private final String reasonPhrase;

	private QoSReasonPhrase(String toString) {
		this.reasonPhrase = toString;
	}

	public String toString() {
		return reasonPhrase;
	}

}

